---
abstract: 'Method declarations with type constraints and no source filter'
author:
  - 'Florian Ragwitz'
build_requires:
  Test::Exception: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Method-Signatures
no_index:
  directory:
    - inc
    - t
requires:
  Devel::Declare: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Meta::Signature::Combined: 0
  Perl6::Signature: 0.03
  Scope::Guard: 0
  Sub::Name: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
