---
abstract: 'Method declarations with type constraints and no source filter'
author:
  - 'Florian Ragwitz'
build_requires:
  Test::Exception: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Method-Signatures
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::EndOfScope: 0.07
  Devel::Declare: 0.003004
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Meta::Signature::Combined: 0
  MooseX::Types::Moose: 0
  Parse::Method::Signatures: 1.002000
  namespace::clean: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=MooseX-Method-Signatures
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rafl/moosex-method-signatures.git
version: 0.08
