---
abstract: 'Method declarations with type constraints and no source filter'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Ash Berlin <ash@cpan.org>'
  - 'Cory Watson <gphat@cpan.org>'
  - 'Daniel Ruoso <daniel@ruoso.com>'
  - 'Dave Rolsky <autarch@urth.org>'
  - 'Hakim Cassimally <hakim.cassimally@gmail.com>'
  - 'Jonathan Scott Duff <duff@pobox.com>'
  - 'Justin Hunter <justin.d.hunter@gmail.com>'
  - 'Kent Fredric <kentfredric@gmail.com>'
  - 'Maik Hentsche <maik.hentsche@amd.com>'
  - 'Matt Kraai <kraai@ftbfs.org>'
  - 'Rhesa Rozendaal <rhesa@cpan.org>'
  - 'Ricardo SIGNES <rjbs@cpan.org>'
  - 'Steffen Schwigon <ss5@renormalist.net>'
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
  - 'Nicholas Perez <nperez@cpan.org>'
  - 'Karen Etheridge <ether@cpan.org>'
build_requires:
  Data::Dumper: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Moose::Role: 0
  Test::CheckDeps: 0.002
  Test::Deep: 0
  Test::Fatal: 0
  Test::Moose: 0
  Test::More: 0.89
  attributes: 0
  metaclass: 0
  namespace::clean: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Method-Signatures
provides:
  MooseX::Method::Signatures:
    file: lib/MooseX/Method/Signatures.pm
    version: 0.44
  MooseX::Method::Signatures::Meta::Method:
    file: lib/MooseX/Method/Signatures/Meta/Method.pm
    version: 0.44
  MooseX::Method::Signatures::Types:
    file: lib/MooseX/Method/Signatures/Types.pm
    version: 0.44
requires:
  B::Hooks::EndOfScope: 0.10
  Carp: 0
  Context::Preserve: 0
  Devel::Declare: 0.005011
  Devel::Declare::Context::Simple: 0
  Eval::Closure: 0
  Module::Runtime: 0.012
  Moose: 0.89
  Moose::Meta::Class: 0
  Moose::Meta::Method: 0
  Moose::Util: 0
  Moose::Util::TypeConstraints: 0
  MooseX::LazyRequire: 0.06
  MooseX::Meta::TypeConstraint::ForceCoercion: 0
  MooseX::Types: 0.35
  MooseX::Types::Moose: 0.19
  MooseX::Types::Structured: 0.24
  MooseX::Types::Util: 0
  Parse::Method::Signatures: 1.003014
  Parse::Method::Signatures::Param::Named: 0
  Parse::Method::Signatures::Param::Placeholder: 0
  Parse::Method::Signatures::TypeConstraint: 0
  Parse::Method::Signatures::Types: 0
  Scalar::Util: 0
  Sub::Name: 0
  Task::Weaken: 0
  Text::Balanced: 0
  aliased: 0
  namespace::autoclean: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=MooseX-Method-Signatures
  homepage: https://github.com/karenetheridge/moosex-method-signatures
  repository: https://github.com/karenetheridge/moosex-method-signatures.git
version: 0.44
x_Dist_Zilla:
  perl:
    version: 5.016002
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@FLORA/@Basic/GatherDir'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@FLORA/@Basic/PruneCruft'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@FLORA/@Basic/ManifestSkip'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@FLORA/@Basic/MetaYAML'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::License
      name: '@FLORA/@Basic/License'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@FLORA/@Basic/Readme'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@FLORA/@Basic/ExtraTests'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@FLORA/@Basic/ExecDir'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@FLORA/@Basic/ShareDir'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@FLORA/@Basic/MakeMaker'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@FLORA/@Basic/Manifest'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@FLORA/@Basic/TestRelease'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@FLORA/@Basic/ConfirmRelease'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@FLORA/@Basic/UploadToCPAN'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@FLORA/MetaConfig'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@FLORA/MetaJSON'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@FLORA/PkgVersion'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@FLORA/PodSyntaxTests'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@FLORA/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@FLORA/MetaResources'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@FLORA/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@FLORA/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@FLORA/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@FLORA/AutoPrereqs'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: DevelopRequires
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 2.002
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: 0.28
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: Git::Describe
      version: 0.002
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: MetaProvides::Package
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: 1.003
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmeAnyFromPod
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: Test::Pod::LinkCheck
      version: 1.001
    -
      class: Dist::Zilla::Plugin::Test::Pod::No404s
      name: Test::Pod::No404s
      version: 1.001
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CheckPrereqsIndexed
      version: 0.007
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: Test::MinimumVersion
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: Test::CPAN::Changes
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Test::ChangesHasContent
      name: Test::ChangesHasContent
      version: 0.006
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: MetaTests
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      name: Test::CheckDeps
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: Git::Remote::Check
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: Git::CheckFor::CorrectBranch
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: Git::Check
      version: 2.002
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: Git::Commit
      version: 2.002
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: Git::Tag
      version: 2.002
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: Git::Push
      version: 2.002
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: InstallRelease
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Clean
      name: Clean
      version: 0.07
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300028
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300028
x_authority: cpan:FLORA
