use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Florian
Ragwitz
rafl
Karen
Etheridge
ether
Ash
Berlin
ash
Daniel
Ruoso
daniel
Nicholas
Perez
nperez
Yanick
Champoux
yanick
Cory
Watson
gphat
Justin
Hunter
justin
Rhesa
Rozendaal
rhesa
Hakim
Cassimally
osfameron
Kent
Fredric
kentfredric
Lukas
Mai
mai
Dagfinn
Ilmari
Mannsåker
ilmari
Matt
Kraai
kraai
Ricardo
SIGNES
rjbs
Steffen
Schwigon
ss5
Dave
Rolsky
autarch
Jesse
Luehrs
doy
Jonathan
Rockway
jon
Scott
Duff
duff
Maik
Hentsche
maik
Sebastian
Willert
willert
lib
MooseX
Method
Signatures
Types
Meta
