use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006001
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Florian
Ragwitz
rafl
Ash
Berlin
ash
Cory
Watson
gphat
Dagfinn
Ilmari
Mannsåker
ilmari
Daniel
Ruoso
daniel
Dave
Rolsky
autarch
Hakim
Cassimally
osfameron
Jesse
Luehrs
doy
Jonathan
Rockway
jon
Scott
Duff
duff
Justin
Hunter
justin
Karen
Etheridge
ether
Kent
Fredric
kentfredric
Lukas
Mai
mai
Maik
Hentsche
maik
Matt
Kraai
kraai
Nicholas
Perez
nperez
Rhesa
Rozendaal
rhesa
Ricardo
SIGNES
rjbs
Sebastian
Willert
willert
Steffen
Schwigon
ss5
Yanick
Champoux
yanick
lib
MooseX
Method
Signatures
Types
Meta
